# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_add_Booking_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotTerminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
